### ISSUE TITLE
files.mcupdater.com is down -> MCUpdater doesn't start

### ISSUE THREAD

**Issue by gelraen** [MCUpdater/MCU-Bootstrap#4]
Please add some redundancy so single-machine outage doesn't kill MCUpdater for everyone

**Comment by smbarbour** [comment]
Redundancy was added in 202c3deb9520cb83062d2e9194ce90d2f7eb6815 back in April.  The site is up and is hosted on a major service which has not reported any outages.

**Comment by gelraen** [comment]
Hm, the commit you mention adds fallback to a local `Bootstrap-cache.xml` file, right? I don't have this file in `~/Library/Application\ Support/MCUpdater` on my machine, is it deleted at some stage?

What I've experienced today for about 15 minutes:
1. MCUpdater complaining about `No configuration found that matches distribution "Release" for Java 1.8` on launch attempt
2. `wget http://files.mcupdater.com/Bootstrap.xml` was failing with a timeout
3. http://isup.me/files.mcupdater.com was saying that it is down.

**Comment by smbarbour** [comment]
If the bootstrap version you have was from before that commit, then it obviously won't do that.

**Comment by gelraen** [comment]
Oh, so bootstrap doesn't update itself? That's something I didn't consider :D Thanks for the hint, I'll go and update it now.
