### ISSUE TITLE
More than one pack in config.properties

### ISSUE THREAD

**Issue by endumiuz** [MCUpdater/MCU-Bootstrap#8]
Is it possible to specify more than one pack in config.properties?
Something like `defaultPack = [http://example.com/pack1.xml, http://example.com/pack2.xml]`

**Comment by smbarbour** [comment]
Although it is not possible to specify multiple XML files for the default pack, you can have an XML file that has multiple packs in it as the default.

**Comment by endumiuz** [comment]
It works! Thanks! :+1:
